include: package:very_good_analysis/analysis_options.yaml


linter:
  rules:
    omit_local_variable_types: false
    public_member_api_docs: false
    sort_constructors_first: false
    sort_unnamed_constructors_first: false
    lines_longer_than_80_chars: false
