name: bluetooth_repository
description: A new Flutter package project.
version: 0.0.1
homepage: null

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter: null
